// ────────────────────────────────────────────────────────────────────────────
// ⚠️  MIRROR dari Supabase Edge Function "my20fit-otp" (project cpvzwqptzcxnwzfzgrmt, verify_jwt=false).
// Snapshot untuk git. Repo ini TIDAK auto-deploy edge functions — kalau ada
// perubahan, WAJIB deploy ulang manual ke Supabase (supabase functions deploy my20fit-otp,
// atau Supabase MCP deploy_edge_function). Jangan edit lalu lupa deploy.
// ────────────────────────────────────────────────────────────────────────────

import { createClient } from "jsr:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(o,s=200)=>new Response(JSON.stringify(o),{status:s,headers:{...cors,"Content-Type":"application/json"}});
async function sha256(s){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("");}
function gen6(){const a=new Uint32Array(1);crypto.getRandomValues(a);return String(100000+(a[0]%900000));}
async function sendEmail(to,otp,ttl,title){const key=Deno.env.get("MAILTRAP_API_KEY");if(!key){console.log("[DEV] OTP "+to+": "+otp);return{sent:false};}const url=Deno.env.get("MAILTRAP_API_URL")||"https://send.api.mailtrap.io/api/send";const from=Deno.env.get("MAIL_FROM_EMAIL")||"no-reply@20fit.id";const head=title||"Kode Verifikasi 20fit";const html="<div style='font-family:Arial;max-width:480px;margin:auto'><h2 style='color:#C41101'>"+head+"</h2><p>Kode kamu:</p><div style='font-size:30px;font-weight:bold;letter-spacing:8px;background:#f4efe6;padding:14px;text-align:center;border-radius:10px'>"+otp+"</div><p style='color:#888;font-size:13px'>Berlaku "+ttl+" menit.</p></div>";const r=await fetch(url,{method:"POST",headers:{"Authorization":"Bearer "+key,"Content-Type":"application/json"},body:JSON.stringify({from:{email:from,name:"20fit"},to:[{email:to}],subject:head,html,category:"OTP"})});if(!r.ok){return{sent:false,error:"Mailtrap "+r.status+": "+(await r.text())};}return{sent:true};}
async function verifyOtp(sb,email,code,MASTER){if(MASTER&&code===MASTER)return true;const q=await sb.from("my20fit_email_otp").select("*").eq("email",email).eq("code_hash",await sha256(code)).is("consumed_at",null).gt("expires_at",new Date().toISOString()).order("created_at",{ascending:false}).limit(1);if(!q.data||q.data.length===0)return false;await sb.from("my20fit_email_otp").update({consumed_at:new Date().toISOString()}).eq("id",q.data[0].id);return true;}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{const b=await req.json();const email=(b.email||"").trim().toLowerCase();const code=(b.code||"").trim();if(!email)return json({error:"email wajib"},400);const sb=createClient(Deno.env.get("SUPABASE_URL"),Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"));const TTL=parseInt(Deno.env.get("OTP_TTL_MINUTES")||"10");const MASTER=Deno.env.get("MASTER_OTP")||"";
if(b.action==="exists"){const p=await sb.from("my20fit_profile").select("auth_user_id").eq("email",email).limit(1);return json({ok:true,exists:!!(p.data&&p.data.length)});}
if(b.action==="send"){const since=new Date(Date.now()-600000).toISOString();const c=await sb.from("my20fit_email_otp").select("*",{count:"exact",head:true}).eq("email",email).gte("created_at",since);if((c.count||0)>=5)return json({error:"Terlalu sering. Coba lagi nanti."},429);const otp=gen6();await sb.from("my20fit_email_otp").delete().eq("email",email).is("consumed_at",null);await sb.from("my20fit_email_otp").insert({email,code_hash:await sha256(otp),purpose:b.purpose||"verify",expires_at:new Date(Date.now()+TTL*60000).toISOString()});const r=await sendEmail(email,otp,TTL);const p={ok:true,sent:r.sent};if(r.error)p.mail_error=r.error;if(!r.sent&&!r.error)p.devCode=otp;return json(p);}
if(b.action==="verify"){if(!code)return json({error:"kode wajib"},400);const ok=await verifyOtp(sb,email,code,MASTER);if(!ok)return json({error:"Kode salah atau kedaluwarsa."},400);return json({ok:true,verified:true});}
if(b.action==="reset"){const pw=b.password||"";if(!code)return json({error:"kode wajib"},400);if(pw.length<8)return json({error:"Password minimal 8 karakter."},400);const ok=await verifyOtp(sb,email,code,MASTER);if(!ok)return json({error:"Kode salah atau kedaluwarsa."},400);const p=await sb.from("my20fit_profile").select("auth_user_id").eq("email",email).limit(1);if(!p.data||p.data.length===0)return json({error:"Akun tidak ditemukan untuk email ini."},404);const u=await sb.auth.admin.updateUserById(p.data[0].auth_user_id,{password:pw});if(u.error)return json({error:u.error.message},500);return json({ok:true,reset:true});}
if(b.action==="login_send"){const prof=await sb.from("my20fit_profile").select("auth_user_id").eq("email",email).limit(1);if(!prof.data||prof.data.length===0)return json({error:"not_registered",message:"Email belum terdaftar di app."},404);const since=new Date(Date.now()-600000).toISOString();const c=await sb.from("my20fit_email_otp").select("*",{count:"exact",head:true}).eq("email",email).gte("created_at",since);if((c.count||0)>=6)return json({error:"Terlalu sering. Coba lagi nanti."},429);const g=await sb.auth.admin.generateLink({type:"magiclink",email});if(g.error)return json({error:g.error.message},500);const otp=g.data&&g.data.properties&&g.data.properties.email_otp;if(!otp)return json({error:"Gagal membuat kode login."},500);try{await sb.from("my20fit_email_otp").insert({email,code_hash:await sha256("login"),purpose:"login",expires_at:new Date(Date.now()+TTL*60000).toISOString()});}catch(e){}const r=await sendEmail(email,otp,60,"Kode Login 20fit");const p={ok:true,sent:r.sent};if(r.error)p.mail_error=r.error;if(!r.sent&&!r.error)p.devCode=otp;return json(p);}
return json({error:"action tidak dikenal"},400);}catch(e){return json({error:String(e&&e.message||e)},500);}});
